// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4iVg9C-0Y0zJ75HfUtRIUVgCFzYjOGAI',
    appId: '1:231431457861:web:66f321b1c0cee18b36e72c',
    messagingSenderId: '231431457861',
    projectId: 'mycs-b0307',
    authDomain: 'mycs-b0307.firebaseapp.com',
    storageBucket: 'mycs-b0307.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADLTkmZmBzZnHnQ2o3agdI9O2ojfW7k1c',
    appId: '1:231431457861:android:01b8531a7017440f36e72c',
    messagingSenderId: '231431457861',
    projectId: 'mycs-b0307',
    storageBucket: 'mycs-b0307.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvPRlq2TOCtsbOpBjNiGuS1G0Mws5gbhM',
    appId: '1:231431457861:ios:cdb3e354c6d94a6336e72c',
    messagingSenderId: '231431457861',
    projectId: 'mycs-b0307',
    storageBucket: 'mycs-b0307.firebasestorage.app',
    iosBundleId: 'com.example.mycs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvPRlq2TOCtsbOpBjNiGuS1G0Mws5gbhM',
    appId: '1:231431457861:ios:cdb3e354c6d94a6336e72c',
    messagingSenderId: '231431457861',
    projectId: 'mycs-b0307',
    storageBucket: 'mycs-b0307.firebasestorage.app',
    iosBundleId: 'com.example.mycs',
  );
}
